name: Check fluent files for changed strings without new ID

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check for unchanged IDs
        run: |
          diff=$( git diff --name-only ${{ github.event.pull_request.base.sha }} $GITHUB_SHA )
          files+="$( echo "$diff" | grep '\.ftl$' || true )"
          for file in $files; do
            file_old=$(printf $file | sed s/.ftl$/old.ftl/)
            file_new=$(printf $file | sed s/.ftl$/new.ftl/)
            git show ${{ github.event.pull_request.base.sha }}:$file > $file_old
            git show $GITHUB_SHA:$file > $file_new
            errorArray+=( "$file_old" "$file_new" )
          done
          echo $errorArray
          #python ./.github/scripts/unchanged-ids/fluent.syntax/parse_messages_terms_to_dict.py ${errorArray[@]}
