name: Tests
on:
  push:
    branches:
      - main
    paths:
      - 'locale/**/*.po'
  workflow_dispatch:
jobs:
  run-test:
    # Pontoon creates one commit per locale every 10 minutes, only run on
    # the latest commit of the batch.
    concurrency:
        group: ${{ github.ref }}
        cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux packages
        run: |
          sudo apt update
          sudo apt install gettext graphicsmagick -y
      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - name: Install global npm packages
        run: |
          npm install -g grunt-cli
      - name: Clone l10n repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install npm packages
        run: |
          npm ci
      - name: Run tests
        run: |
          npm test
